[package]
name = "wgpu-tensor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.13.1"
smallvec = "1.10.0"
wgpu = "0.16.1"
